services:

  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: laboratorio-api

    ports:
      - "8000:8000"

    depends_on:
      - mysql

    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: laboratorio
      MYSQL_USER: laboratorio
      MYSQL_PASSWORD: laboratorio

    restart: unless-stopped


  mysql:
    image: mysql:8

    container_name: laboratorio-mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laboratorio
      MYSQL_USER: laboratorio
      MYSQL_PASSWORD: laboratorio

    volumes:
      - mysql_data:/var/lib/mysql

    restart: unless-stopped


volumes:
  mysql_data: